# Generated by Django 5.0 on 2025-05-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
