# Generated by Django 5.0 on 2025-05-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_patient_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="insurance_number",
            field=models.CharField(blank=True, max_length=20, verbose_name="保険者番号"),
        ),
    ]
