# Generated by Django 5.0 on 2025-05-17 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_patient_insurance_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="admission_date",
            field=models.DateField(blank=True, null=True, verbose_name="入院日"),
        ),
        migrations.AddField(
            model_name="patient",
            name="first_visit_date",
            field=models.DateField(blank=True, null=True, verbose_name="初診日"),
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("measured", models.DateTimeField(verbose_name="測定日時")),
                (
                    "celsius",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="体温(℃)"
                    ),
                ),
                (
                    "pulse",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="脈拍(回/分)"
                    ),
                ),
                (
                    "systolic",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="収縮期血圧(mmHg)"
                    ),
                ),
                (
                    "diastolic",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="拡張期血圧(mmHg)"
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="体重(kg)",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.patient"
                    ),
                ),
            ],
            options={
                "verbose_name": "バイタルサイン",
                "verbose_name_plural": "バイタルサイン",
                "ordering": ["measured"],
            },
        ),
        migrations.DeleteModel(
            name="Temperature",
        ),
    ]
